fix FTBS on debian: missing statement after label
Compilers on recent Debian (gcc as well as clang) break compilation if
there's no statement after a label:

> ../../src/r128_driver.c:571:1: error: expected statement
> }

Signed-off-by: Enrico Weigelt, metux IT consult <info@metux.net>
Part-of: <https://gitlab.freedesktop.org/xorg/driver/xf86-video-r128/-/merge_requests/12>